// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaub689q1THqMSzk7-jX02GSarhZMJtA',
    appId: '1:335840565919:web:789f3cbfa6ec2f5626a0aa',
    messagingSenderId: '335840565919',
    projectId: 'graduation-project-22',
    authDomain: 'graduation-project-22.firebaseapp.com',
    databaseURL: 'https://graduation-project-22-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5VeRQo_6CT2ZqI7au7f2TiG8AGbajtM',
    appId: '1:335840565919:android:d5a62e0e569b7b3826a0aa',
    messagingSenderId: '335840565919',
    projectId: 'graduation-project-22',
    databaseURL: 'https://graduation-project-22-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSudkRDYXcJMfWLNBM1FXXRAavtbi9evg',
    appId: '1:335840565919:ios:93592dd0170de40526a0aa',
    messagingSenderId: '335840565919',
    projectId: 'graduation-project-22',
    databaseURL: 'https://graduation-project-22-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-22.firebasestorage.app',
    iosBundleId: 'com.example.cashflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSudkRDYXcJMfWLNBM1FXXRAavtbi9evg',
    appId: '1:335840565919:ios:93592dd0170de40526a0aa',
    messagingSenderId: '335840565919',
    projectId: 'graduation-project-22',
    databaseURL: 'https://graduation-project-22-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-22.firebasestorage.app',
    iosBundleId: 'com.example.cashflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbaub689q1THqMSzk7-jX02GSarhZMJtA',
    appId: '1:335840565919:web:b00f38a1d569721126a0aa',
    messagingSenderId: '335840565919',
    projectId: 'graduation-project-22',
    authDomain: 'graduation-project-22.firebaseapp.com',
    databaseURL: 'https://graduation-project-22-default-rtdb.firebaseio.com',
    storageBucket: 'graduation-project-22.firebasestorage.app',
  );

}